swagger: '2.0'
info:
  description: Server to manage and analyze Threat Models
  version: 1.0.0
  title: Threat Model Assessment App
tags:
  - name: threat-model
    description: Create, save and get events
paths:
  /threat/save:
      post:
        tags:
          - threat
        summary: Save threat models
        description: Save threat models from the frontend
        operationId: saveThreatModel
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - in: body
            name: body
            description: Threat Model
            schema:
              $ref: '#/definitions/ThreatModel'
        responses:
          '201':
            description: Created test
          '401':
            description: Unauthorized
          '405':
            description: Failed to create event
definitions:
  ThreatModel:
    type: object
    properties:
      interactors:
        type: array
        items:
          $ref: '#/definitions/Interactor'
      dataFlows:
        type: array
        items:
          $ref: '#/definitions/DataFlow'
      dataStores:
        type: array
        items:
          $ref: '#/definitions/DataStore'
      processes:
        type: array
        items:
          $ref: '#/definitions/Process'
      collections:
        type: array
        items:
          $ref: '#/definitions/Collection'
  Interactor:
    type: object
    properties:
      id:
        type: string
      coordinates:
        $ref: '#/definitions/PointCoordinates'
      name:
        type: string
      type:
        $ref: '#/definitions/InteractorType'
      genericOptions:
        $ref: '#/definitions/GenericInteractorOptions'
  PointCoordinates:
    type: object
    properties:
      xCoord:
        type: number
      yCoord:
        type: number
  InteractorType:
    type: string
    enum:
      - Generic Interactor
      - Human User
      - Browser
      - External Web Application
      - External Web Service
      - Authorization Provider
      - Megaservice
      - Windows Runtime
  GenericInteractorOptions:
    type: object
    properties:
      authenticatesItself:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      destinationAuthenticated:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      human:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
  GenericOptionsTrueFalseEnum:
    type: string
    enum:
      - true
      - false
      - notSelected
  DataFlow:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      position:
        type: string
        enum:
          - center
          - bottom
          - top
      startCoords:
        $ref: '#/definitions/PointCoordinates'
      endCoords:
        $ref: '#/definitions/PointCoordinates'
      startElement:
        type: object
        properties:
          id:
            type: string
          coordinates:
            $ref: '#/definitions/PointCoordinates'
      endElement:
        type: object
        properties:
          id:
            type: string
          coordinates:
            $ref: '#/definitions/PointCoordinates'
      type:
        $ref: '#/definitions/DataFlowType'
      genericOptions:
        $ref: '#/definitions/GenericDataFlowOptions'
  GenericDataFlowOptions:
    type: object
    properties:
      physicalNetwork:
        type: string
        enum:
          - wire
          - wifi
          - 2G-4G
          - bluetooth
          - notSelected
      sourceAuthenticated:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      destinationAuthenticated:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      providesConfidentiality:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      providesIntegrity:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      transmitsXML:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      containsCookies:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      soapPayload:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      restPayload:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      rssPayload:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      jsonPayload:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
  DataFlowType:
    type: string
    enum:
      - Generic Data Flow
      - ALCP
      - Binary Data Flow
      - HTTP Data Flow
      - HTTPS Data Flow
      - IOCTL Interface
      - IPsec Data Flow
      - Named Pipe Data Flow
      - RPC / DCOM
      - SMB Data Flow
      - User Data Protocol
  DataStore:
    type: object
    properties:
      id:
        type: string
      coordinates:
        $ref: '#/definitions/PointCoordinates'
      name:
        type: string
      type:
        $ref: '#/definitions/DataStoreType'
      genericOptions:
        $ref: '#/definitions/GenericDataStoreOptions'
  GenericDataStoreOptions:
    type: object
    properties:
      storesCredentials:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      storesLogData:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      encrypted:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      signed:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      backup:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      writeAccess:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      removableStorage:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      shared:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
  DataStoreType:
    type: string
    enum:
      - Generic Data Store
      - Cache
      - Cloud Storage
      - Configuration File
      - Cookies
      - Device
      - File System
      - HTML5 Local Storage
      - Non-Relational Database
      - Registry Hive
      - SQL Database
  Process:
    type: object
    properties:
      id:
        type: string
      coordinates:
        $ref: '#/definitions/PointCoordinates'
      name:
        type: string
      type:
        $ref: '#/definitions/ProcessType'
      genericOptions:
        $ref: '#/definitions/GenericProcessOptions'
  GenericProcessOptions:
    type: object
    properties:
      codeType:
        type: string
        enum:
          - managed
          - unmanaged
          - notSelected
      runningAs:
        type: string
        enum:
          - kernel
          - system
          - networkService
          - localService
          - admin
          - standardUserWithElevation
          - standardUserWithoutElevation
          - windowsStoreApp
          - notSelected
      isolationLevel:
        type: string
        enum:
          - appContainer
          - lowIntegrityLvl
          - moice
          - sandbox
          - notSelected
      acceptsInputsFrom:
        type: string
        enum:
          - anyRemoteInteractor
          - kernelSysOrLocalAdmin
          - localNetworkOrService
          - localStandardUserWithElevation
          - localStandardUserWithoutElevation
          - windowsStoreApps
          - nothing
          - other
          - notSelected
      implAuthenticationMechanism:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      implAuthorizationMechanism:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      implCommunityProtocol:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      sanitizesInput:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
      sanitizesOutput:
        $ref: '#/definitions/GenericOptionsTrueFalseEnum'
  ProcessType:
    type: string
    enum:
      - Generic Process
      - App running non-MS OS
      - Browser Plug-ins
      - Browser Client
      - Kernel Thread
      - Managed Application
      - OS Process
      - Thick Client
      - Thread
      - Virtual Machine
      - Web Application
      - Web Server
      - Web Service
      - Win32 Service
      - Windows Store Process
  Collection:
    type: object
    properties:
      id:
        type: string
      coordinates:
        $ref: '#/definitions/PointCoordinates'
      height:
        type: number
      width:
        type: number
      collectedElements:
        type: array
        items:
          type: string